/* It had generated by DirectStruct v1.13.4 */
#include "IDL_zookeeper_broker_ids.dsc.h"

#ifndef FUNCNAME_DSCLOG_zookeeper_broker_ids
#define FUNCNAME_DSCLOG_zookeeper_broker_ids	DSCLOG_zookeeper_broker_ids
#endif

#ifndef PREFIX_DSCLOG_zookeeper_broker_ids
#define PREFIX_DSCLOG_zookeeper_broker_ids	printf( 
#endif

#ifndef NEWLINE_DSCLOG_zookeeper_broker_ids
#define NEWLINE_DSCLOG_zookeeper_broker_ids	"\n"
#endif

int FUNCNAME_DSCLOG_zookeeper_broker_ids( zookeeper_broker_ids *pst )
{
	int	index[10] = { 0 } ; index[0]++; index[0] = 0 ;
	PREFIX_DSCLOG_zookeeper_broker_ids "zookeeper_broker_ids.host[%s]" NEWLINE_DSCLOG_zookeeper_broker_ids , pst->host );
	PREFIX_DSCLOG_zookeeper_broker_ids "zookeeper_broker_ids.port[%d]" NEWLINE_DSCLOG_zookeeper_broker_ids , pst->port );
	return 0;
}
