/* It had generated by DirectStruct v1.13.0 */
#include "IDL_logpipe_conf.dsc.h"

#ifndef FUNCNAME_DSCLOG_logpipe_conf
#define FUNCNAME_DSCLOG_logpipe_conf	DSCLOG_logpipe_conf
#endif

#ifndef PREFIX_DSCLOG_logpipe_conf
#define PREFIX_DSCLOG_logpipe_conf	printf( 
#endif

#ifndef NEWLINE_DSCLOG_logpipe_conf
#define NEWLINE_DSCLOG_logpipe_conf	"\n"
#endif

int FUNCNAME_DSCLOG_logpipe_conf( logpipe_conf *pst )
{
	int	index[10] = { 0 } ; index[0]++; index[0] = 0 ;
		PREFIX_DSCLOG_logpipe_conf "logpipe_conf._inputs_count[%d]" NEWLINE_DSCLOG_logpipe_conf , pst->_inputs_count );
		for( index[1] = 0 ; index[1] < pst->_inputs_count ; index[1]++ )
		{
		PREFIX_DSCLOG_logpipe_conf "logpipe_conf.inputs[index[1]].input[%s]" NEWLINE_DSCLOG_logpipe_conf , pst->inputs[index[1]].input );
		}
		PREFIX_DSCLOG_logpipe_conf "logpipe_conf._outputs_count[%d]" NEWLINE_DSCLOG_logpipe_conf , pst->_outputs_count );
		for( index[1] = 0 ; index[1] < pst->_outputs_count ; index[1]++ )
		{
		PREFIX_DSCLOG_logpipe_conf "logpipe_conf.outputs[index[1]].output[%s]" NEWLINE_DSCLOG_logpipe_conf , pst->outputs[index[1]].output );
		}
		PREFIX_DSCLOG_logpipe_conf "logpipe_conf.log.log_file[%s]" NEWLINE_DSCLOG_logpipe_conf , pst->log.log_file );
		PREFIX_DSCLOG_logpipe_conf "logpipe_conf.log.log_level[%s]" NEWLINE_DSCLOG_logpipe_conf , pst->log.log_level );
	return 0;
}
